name: Stream Local 3

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  stream:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - name: Start Streaming
        run: |
          sudo apt-get install -y ffmpeg
          ffmpeg -re -analyzeduration 10000000 -probesize 10000000 -i "https://live.fptplay53.net/epzsd1/quangngai_hls.smil/chunklist.m3u8" -c copy -f flv rtmp://42.1.99.192/live/quangngai1 &
          ffmpeg -re -analyzeduration 10000000 -probesize 10000000 -i "https://live.fptplay53.net/epzsd1/quangngai01_hls.smil/chunklist.m3u8" -c copy -f flv rtmp://42.1.99.192/live/quangngai2 &
          ffmpeg -re -analyzeduration 10000000 -probesize 10000000 -i "https://live.fptplay53.net/fnxsd1/quangninh1_hls.smil/chunklist.m3u8" -c copy -f flv rtmp://42.1.99.192/live/quangninh1 &
          ffmpeg -re -analyzeduration 10000000 -probesize 10000000 -i "https://live.fptplay53.net/fnxsd1/quangninh3_hls.smil/chunklist.m3u8" -c copy -f flv rtmp://42.1.99.192/live/quangninh3 &
          ffmpeg -re -analyzeduration 10000000 -probesize 10000000 -i "https://live.fptplay53.net/epzsd1/quangtri_hls.smil/chunklist.m3u8" -c copy -f flv rtmp://42.1.99.192/live/quangtri &
          ffmpeg -re -analyzeduration 10000000 -probesize 10000000 -i "https://live.fptplay53.net/fnxsd1/thanhhoa_hls.smil/chunklist.m3u8" -c copy -f flv rtmp://42.1.99.192/live/thanhhoa &
          ffmpeg -re -analyzeduration 10000000 -probesize 10000000 -i "https://live.fptplay53.net/fnxsd1/tuyenquang_hls.smil/chunklist.m3u8" -c copy -f flv rtmp://42.1.99.192/live/tuyenquang &
          ffmpeg -re -analyzeduration 10000000 -probesize 10000000 -i "https://live.fptplay53.net/fnxsd1/thainguyen_hls.smil/chunklist.m3u8" -c copy -f flv rtmp://42.1.99.192/live/thainguyen &
          ffmpeg -re -analyzeduration 10000000 -probesize 10000000 -i "https://live.fptplay53.net/epzsd1/tayninh01_hls.smil/chunklist.m3u8" -c copy -f flv rtmp://42.1.99.192/live/tayninh &
          ffmpeg -re -analyzeduration 10000000 -probesize 10000000 -i "https://live.fptplay53.net/live/media/vinhlong1/live247-hls-avc/vinhlong1-avc1_5600000=10000-mp4a_131600=20000.m3u8" -c copy -f flv rtmp://42.1.99.192/live/vinhlong1 &
          ffmpeg -re -analyzeduration 10000000 -probesize 10000000 -i "https://live.fptplay53.net/live/media/vinhlong2/live247-hls-avc/vinhlong2-avc1_5600000=10000-mp4a_131600=20000.m3u8" -c copy -f flv rtmp://42.1.99.192/live/vinhlong2 &
          ffmpeg -re -analyzeduration 10000000 -probesize 10000000 -i "https://live.fptplay53.net/live/media/vinhlong3/live247-hls-avc/vinhlong3-avc1_5600000=10000-mp4a_131600=20000.m3u8" -c copy -f flv rtmp://42.1.99.192/live/vinhlong3 &
          ffmpeg -re -analyzeduration 10000000 -probesize 10000000 -i "https://live.fptplay53.net/epzhd2/vinhlong4hd_vhls.smil/chunklist.m3u8" -c copy -f flv rtmp://42.1.99.192/live/vinhlong4 &
          ffmpeg -re -analyzeduration 10000000 -probesize 10000000 -i "https://live.fptplay53.net/epzsd1/vinhlong5_vhls.smil/chunklist.m3u8" -c copy -f flv rtmp://42.1.99.192/live/vinhlong5 &
          ffmpeg -re -analyzeduration 10000000 -probesize 10000000 -i "https://live.fptplay53.net/epzsd1/dongthap_vhls.smil/chunklist.m3u8" -c copy -f flv rtmp://42.1.99.192/live/dongthap1 &
          ffmpeg -re -analyzeduration 10000000 -probesize 10000000 -i "https://live.fptplay53.net/epzsd1/dongthaphd_vhls.smil/chunklist.m3u8" -c copy -f flv rtmp://42.1.99.192/live/dongthap2 &
          wait
