name: Local Channels Streamer

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  stream-local-1:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - name: Install FFmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg
      - name: Stream Local 1
        run: |
          ffmpeg -re -i "https://sgchill.duckdns.org/source/fptplay.m3u8?id=dongthap1" -c copy -f flv rtmp://42.1.99.192/live/dongthap1 &
          ffmpeg -re -i "https://sgchill.duckdns.org/source/fptplay.m3u8?id=dongthap2" -c copy -f flv rtmp://42.1.99.192/live/dongthap2 &
          ffmpeg -re -i "https://sgchill.duckdns.org/source/fptplay.m3u8?id=gialai" -c copy -f flv rtmp://42.1.99.192/live/gialai &
          ffmpeg -re -i "https://sgchill.duckdns.org/source/fptplay.m3u8?id=hue" -c copy -f flv rtmp://42.1.99.192/live/hue &
          ffmpeg -re -i "https://sgchill.duckdns.org/source/fptplay.m3u8?id=hanoi1" -c copy -f flv rtmp://42.1.99.192/live/hanoi1 &
          ffmpeg -re -i "https://sgchill.duckdns.org/source/fptplay.m3u8?id=hanoi2" -c copy -f flv rtmp://42.1.99.192/live/hanoi2 &
          ffmpeg -re -i "https://sgchill.duckdns.org/source/fptplay.m3u8?id=haiphong" -c copy -f flv rtmp://42.1.99.192/live/haiphong &
          wait
  stream-local-2:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - name: Install FFmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg
      - name: Stream Local 2
        run: |
          ffmpeg -re -i "https://sgchill.duckdns.org/source/fptplay.m3u8?id=haiphong3" -c copy -f flv rtmp://42.1.99.192/live/haiphong3 &
          ffmpeg -re -i "https://sgchill.duckdns.org/source/fptplay.m3u8?id=hatinh" -c copy -f flv rtmp://42.1.99.192/live/hatinh &
          ffmpeg -re -i "https://sgchill.duckdns.org/source/fptplay.m3u8?id=hungyen" -c copy -f flv rtmp://42.1.99.192/live/hungyen &
          ffmpeg -re -i "https://sgchill.duckdns.org/source/fptplay.m3u8?id=khanhhoa" -c copy -f flv rtmp://42.1.99.192/live/khanhhoa &
          ffmpeg -re -i "https://sgchill.duckdns.org/source/fptplay.m3u8?id=laocai" -c copy -f flv rtmp://42.1.99.192/live/laocai &
          ffmpeg -re -i "https://sgchill.duckdns.org/source/fptplay.m3u8?id=laichau" -c copy -f flv rtmp://42.1.99.192/live/laichau &
          ffmpeg -re -i "https://sgchill.duckdns.org/source/fptplay.m3u8?id=lamdong1" -c copy -f flv rtmp://42.1.99.192/live/lamdong1 &
          ffmpeg -re -i "https://sgchill.duckdns.org/source/fptplay.m3u8?id=lamdong2" -c copy -f flv rtmp://42.1.99.192/live/lamdong2 &
          wait
