name: Stream Local 2

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  stream:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - name: Start Streaming
        run: |
          sudo apt-get install -y ffmpeg
          ffmpeg -re -analyzeduration 10000000 -probesize 10000000 -i "https://live.fptplay53.net/epzsd1/gialai01_hls.smil/chunklist.m3u8" -c copy -f flv rtmp://42.1.99.192/live/gialai &
          ffmpeg -re -analyzeduration 10000000 -probesize 10000000 -i "https://live.fptplay53.net/epzsd1/hue_hls.smil/chunklist.m3u8" -c copy -f flv rtmp://42.1.99.192/live/hue &
          ffmpeg -re -analyzeduration 10000000 -probesize 10000000 -i "https://live.fptplay53.net/fnxhd2/hanoitv1_vhls.smil/chunklist.m3u8" -c copy -f flv rtmp://42.1.99.192/live/hanoi1 &
          ffmpeg -re -analyzeduration 10000000 -probesize 10000000 -i "https://live.fptplay53.net/fnxhd1/hntv2_vhls.smil/chunklist.m3u8" -c copy -f flv rtmp://42.1.99.192/live/hanoi2 &
          ffmpeg -re -analyzeduration 10000000 -probesize 10000000 -i "https://live.fptplay53.net/live/media/haiphong/live-hls-avc/haiphong-avc1_4000000=10000-mp4a_131600=20000.m3u8" -c copy -f flv rtmp://42.1.99.192/live/haiphong &
          ffmpeg -re -analyzeduration 10000000 -probesize 10000000 -i "https://live.fptplay53.net/fnxsd1/haiphongplus_hls.smil/chunklist.m3u8" -c copy -f flv rtmp://42.1.99.192/live/haiphong3 &
          ffmpeg -re -analyzeduration 10000000 -probesize 10000000 -i "https://live.fptplay53.net/fnxsd1/hatinh_hls.smil/chunklist.m3u8" -c copy -f flv rtmp://42.1.99.192/live/hatinh &
          ffmpeg -re -analyzeduration 10000000 -probesize 10000000 -i "https://live.fptplay53.net/fnxsd1/hungyen_2000.stream/chunklist.m3u8" -c copy -f flv rtmp://42.1.99.192/live/hungyen &
          ffmpeg -re -analyzeduration 10000000 -probesize 10000000 -i "https://live.fptplay53.net/epzsd1/khanhhoa_hls.smil/chunklist.m3u8" -c copy -f flv rtmp://42.1.99.192/live/khanhhoa &
          ffmpeg -re -analyzeduration 10000000 -probesize 10000000 -i "https://live.fptplay53.net/fnxsd1/laocai_hls.smil/chunklist.m3u8" -c copy -f flv rtmp://42.1.99.192/live/laocai &
          ffmpeg -re -analyzeduration 10000000 -probesize 10000000 -i "https://live.fptplay53.net/fnxsd1/laichau_hls.smil/chunklist.m3u8" -c copy -f flv rtmp://42.1.99.192/live/laichau &
          ffmpeg -re -analyzeduration 10000000 -probesize 10000000 -i "https://live.fptplay53.net/epzsd1/lamdong_hls.smil/chunklist.m3u8" -c copy -f flv rtmp://42.1.99.192/live/lamdong1 &
          ffmpeg -re -analyzeduration 10000000 -probesize 10000000 -i "https://live.fptplay53.net/epzsd1/lamdong02_hls.smil/chunklist.m3u8" -c copy -f flv rtmp://42.1.99.192/live/lamdong2 &
          ffmpeg -re -analyzeduration 10000000 -probesize 10000000 -i "https://live.fptplay53.net/fnxsd1/nghean_hls.smil/chunklist.m3u8" -c copy -f flv rtmp://42.1.99.192/live/nghean &
          ffmpeg -re -analyzeduration 10000000 -probesize 10000000 -i "https://live.fptplay53.net/fnxsd1/phutho_hls.smil/chunklist.m3u8" -c copy -f flv rtmp://42.1.99.192/live/phutho &
          wait
