name: Stream HTV

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  stream:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - name: Start Streaming
        run: |
          sudo apt-get install -y ffmpeg
          ffmpeg -re -analyzeduration 10000000 -probesize 10000000 -i "https://live.fptplay53.net/epzhd1/htv1_hls.smil/chunklist.m3u8" -c copy -f flv rtmp://42.1.99.192/live/htv1 &
          ffmpeg -re -analyzeduration 10000000 -probesize 10000000 -i "https://live.fptplay53.net/epzhd1/htv2hd_vhls.smil/chunklist.m3u8" -c copy -f flv rtmp://42.1.99.192/live/htv2 &
          ffmpeg -re -analyzeduration 10000000 -probesize 10000000 -i "https://live.fptplay53.net/epzhd1/htv3_hls.smil/chunklist.m3u8" -c copy -f flv rtmp://42.1.99.192/live/htv3 &
          ffmpeg -re -analyzeduration 10000000 -probesize 10000000 -i "https://live.fptplay53.net/epzhd1/htv4_hls.smil/chunklist.m3u8" -c copy -f flv rtmp://42.1.99.192/live/htv4 &
          ffmpeg -re -analyzeduration 10000000 -probesize 10000000 -i "https://live.fptplay53.net/fnxsd1/btv9_hls.smil/chunklist.m3u8" -c copy -f flv rtmp://42.1.99.192/live/htv5 &
          ffmpeg -re -analyzeduration 10000000 -probesize 10000000 -i "https://live.fptplay53.net/epzch2/htv7hd_abr.smil/chunklist.m3u8" -c copy -f flv rtmp://42.1.99.192/live/htv7 &
          ffmpeg -re -analyzeduration 10000000 -probesize 10000000 -i "https://live.fptplay53.net/epzhd1/htv9hd_vhls.smil/chunklist.m3u8" -c copy -f flv rtmp://42.1.99.192/live/htv9 &
          ffmpeg -re -analyzeduration 10000000 -probesize 10000000 -i "https://live.fptplay53.net/epzhd1/htvcthethao_vhls.smil/chunklist.m3u8" -c copy -f flv rtmp://42.1.99.192/live/htvthethao &
          ffmpeg -re -analyzeduration 10000000 -probesize 10000000 -i "https://live.fptplay53.net/epzhd1/htvcmusic_vhls.smil/chunklist.m3u8" -c copy -f flv rtmp://42.1.99.192/live/htvccanhac &
          ffmpeg -re -analyzeduration 10000000 -probesize 10000000 -i "https://live.fptplay53.net/epzhd1/htvcdulich_vhls.smil/chunklist.m3u8" -c copy -f flv rtmp://42.1.99.192/live/htvcdulich &
          ffmpeg -re -analyzeduration 10000000 -probesize 10000000 -i "https://live.fptplay53.net/epzhd1/htvcgiadinh_vhls.smil/chunklist.m3u8" -c copy -f flv rtmp://42.1.99.192/live/htvcgiadinh &
          ffmpeg -re -analyzeduration 10000000 -probesize 10000000 -i "https://live.fptplay53.net/epzhd1/htvcmovieshd_vhls.smil/chunklist.m3u8" -c copy -f flv rtmp://42.1.99.192/live/htvcphim &
          ffmpeg -re -analyzeduration 10000000 -probesize 10000000 -i "https://live.fptplay53.net/epzhd1/htvcphunu_vhls.smil/chunklist.m3u8" -c copy -f flv rtmp://42.1.99.192/live/htvcphunu &
          ffmpeg -re -analyzeduration 10000000 -probesize 10000000 -i "https://live.fptplay53.net/epzhd1/htvcthuanviethd_vhls.smil/chunklist.m3u8" -c copy -f flv rtmp://42.1.99.192/live/htvcthuanviet &
          ffmpeg -re -analyzeduration 10000000 -probesize 10000000 -i "https://live.fptplay53.net/epzhd1/htvcplus_vhls.smil/chunklist.m3u8" -c copy -f flv rtmp://42.1.99.192/live/htvcplus &
          wait
