name: RTMP Streamer

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *' # Tự chạy mỗi 6 tiếng

jobs:
  stream:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Install FFmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Start Streaming
        run: |
          # Chạy luồng trong đúng 5 giờ 50 phút rồi thoát
          timeout 21000s ffmpeg -hide_banner -loglevel error \
          -user_agent "Mozilla/5.0" \
          -re -i "https://hoiquan.dpdns.org/VTVGo/?sctv1" \
          -c copy -f flv rtmp://42.1.99.192/live/sctv1 || echo "Stream ended"

      - name: Auto-Restart Workflow
        run: |
          # Gửi yêu cầu tới GitHub API để tự kích hoạt lại chính nó
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/stream.yml/dispatches \
            -d '{"ref":"main"}'
