name: Windows CI
on: [push]
jobs:
  build-on-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Display PowerShell version
        run: $PSVersionTable
